resources:
  - namespace.yaml

helmChartInflationGenerator:
  - chartName: promtail
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: promtail
    values: ./promtail/values.yaml
  - chartName: loki
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: loki
    values: ./loki/values.yaml
  - chartName: grafana
    chartRepoUrl: https://grafana.github.io/helm-charts
    releaseNamespace: observability
    releaseName: grafana
    values: ./grafana/values.yaml
